### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#105]
For reference: https://github.com/scottwainstock/pbm/issues/509

The link should be in the dropdown menu (and if you're not logged in, then you get sent to the login page).

**Comment by scottwainstock** [comment]
@RyanTG I gotta make API endpoints for this... should I make it so you can only see your own profile stats, or just leave it open for anyone to put a user_id in and see that user_id's stats?

My vote is for the latter.

**Comment by RyanTG** [comment]
Yeah, the latter would be cool. 

Think it should default to your own, with the option to input others?

**Comment by scottwainstock** [comment]
@RyanTG I'm gonna try and stick with the standard "member" rails form.. so the signature looks like this:       api :GET, '/api/v1/users/:id/profile_info.json', 'Fetch profile info for a user'

**Comment by RyanTG** [comment]
Should/could we add the username form to the website profile page, too? If so, I think part of the value of that would be in the page generating a link, so that people could share profiles.

**Comment by scottwainstock** [comment]
What's "the username form"?

**Comment by scottwainstock** [comment]
Oh you mean like... instead of just "/profile", they'd have to go to
"/users/111/profile"? I can do that.

**Comment by RyanTG** [comment]
Yeah the form where you can enter a username.

That would be cool. We'd have to create a "no user found" message, too, right?

And then ultimately we might want to have a list of all users somewhere (or just users who are active in a particular region? That might not make sense, though, given that the profile page is global)

**Comment by RyanTG** [comment]
That's what you're talking about, right? A field for entering a username?

**Comment by scottwainstock** [comment]
I don't think so, no.

What I thought you meant was...

When user #11 clicks their profile on the website, instead of taking them
to http://pinballmapstaging.herokuapp.com/profile, it'd take them to
http://pinballmapstaging.herokuapp.com/users/11/profile

That way they can share "
http://pinballmapstaging.herokuapp.com/users/11/profile" if they want to
show other people their profile.

**Comment by scottwainstock** [comment]
We could certainly have ANOTHER page that let someone enter a username,
then it redirects them to like "
http://pinballmapstaging.herokuapp.com/users/11/profile" if they entered
user 11's username.

**Comment by RyanTG** [comment]
Oh, when you said "just leave it open for anyone to put a user_id in and see that user_id's stats" you were referring to putting in a user id in the URL? I interpreted that as putting a username in a field/form.

**Comment by RyanTG** [comment]
Reading more carefully (now that I'm at home), I see that you were just talking about the API endpoints in your first comment. 

At any rate, yeah, I like this:

> When user #11 clicks their profile on the website, instead of taking them to http://pinballmapstaging.herokuapp.com/profile, it'd take them to http://pinballmapstaging.herokuapp.com/users/11/profile

And yeah, we could have another page that lets someone enter a username. Or perhaps there can be a div on every profile page containing a form to let them do that.

One thing I've been thinking about is our SEO. Like, we come up a lot in search results when you search a city name and "pinball". But, it's only the main region pages - the individual locations don't show up. If our site was more like Yelp or whatever - with individual pages for each location - then we'd show up even more in results. I know that we DO have individual location pages, but I guess the web crawlers can't find them? Not sure if there's any way to fix that, especially a way to do it without losing our "single page app" format. Maybe it's fine as it is.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/743a8aba273f86e435fdad2fec0f6de0ae253f12
https://github.com/scottwainstock/pbm/commit/a67fa09123d5c47b7409107732904e3e0db2460f

**Comment by scottwainstock** [comment]
@RyanTG e9e393e05c67a451e5539ce70903bf70c2645b46

That's a first draft. Needs styling.

A weird quirk... I have the edited locations list clickable, they take you to the location you edited. However, this breaks things when you are current viewing a region that differs from the region one of your locations was edited in. Does that make sense? The easiest way to handle this was to omit locations from the edited locations list that don't exist in the current region you are viewing. What do you think about that?

**Comment by RyanTG** [comment]
I was out of town today, and will catch up tomorrow.

The part that doesn't quite make sense is that I thought the profile page is global. So I thought that edited locations list would only be available on a page that was region-agnostic. But, when I look at this tomorrow I'm sure it will make sense.

**Comment by RyanTG** [comment]
Can you format the high scores so they look like this:

Machine Name
Score
at Location Name on Date

Like, with the line breaks? I couldn't figure out how to do that in the java file. Usually I use setText(Html.fromhtml()). But I couldn't get that working with the getString functions.

Also, can you change the format of the creation date to: Mar-02-2016 ?

There are some scrolling issues in the bottom half.

Tell me if the style I added is annoying. It has a lot of padding, so it really fills up a lot of space.

Also, I'm not sure how to style the list of edited locations. It seems to be taking the style from another view.

**Comment by scottwainstock** [comment]
create date formatting: 1587c5d49c1bdfe8eb06a69fa00b141d506ca386

**Comment by scottwainstock** [comment]
@RyanTG Formatting for the edited locations is happening here: location_list_listview.xml

Changes to that file will affect Profile, MachineLookupDetail, LocationLookupDetail, and CloseLocations. So, let me know if we need a new one that only affects the Profile page.

**Comment by scottwainstock** [comment]
@RyanTG c18d98d881ed71e662a0c6c480d20156b9eefab0

That's html formatting for the high scores. I put in some <br />s, but you can add whatever else you need.

**Comment by RyanTG** [comment]
I'll check it out tomorrow and see. I need to do a thorough look at the styles on all the pages on the app. When we changed color themes, I sort of just did a bunch of find/replaces with colors. But now I want to look closer.
