### ISSUE TITLE
Donate page

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#106]
Modeled after the webpage. Paypal link + explanation.

**Comment by RyanTG** [comment]
I would try this myself. But I think creating a new page is beyond me.

**Comment by scottwainstock** [comment]
@RyanTG This probably needs some styling, but I think it works: 2893e58fc239ba7c83185b34678660617936cd12

**Comment by RyanTG** [comment]
I'm going to push a small style update to this in a minute. 

But, one thing that's missing is the top menu. Like, there's no "back" button on the top, nor the three-dot menu.

**Comment by scottwainstock** [comment]
Yeah, since this is a menu option page, I ditch the menu. You'll see
similar behavior in "about". You want this reworked?

**Comment by RyanTG** [comment]
Ah. The menu option pages seem inconsistent then. "Suggest a new region" has the menu. "Change Region" has the menu, except it's a DIFFERENT menu (doesn't contain Donate). "About" and "Donate" are the only two without a menu (well, except "Login").

**Comment by RyanTG** [comment]
At any rate, I think it would be nice to have. I just went to the About page, and when I pressed the soft key BACK on my phone, the app closed.

**Comment by RyanTG** [comment]
Well, actually I don't think it HAS to have the menu. But those option pages should be consistent, right?

I feel bad because I keep opening up new issues.

**Comment by scottwainstock** [comment]
Naw, it's cool. I don't mind doing stuff... might as well do it right. It
just means I'll be later on the iOS things.

So... what's the verdict on pages that are loaded from the options menu? Do
they have an options menu option?

**Comment by RyanTG** [comment]
I think they should have it. Otherwise they kind of feel like dead ends.

**Comment by scottwainstock** [comment]
@RyanTG 309d1d67dccbf8c4d0d7a9e188dc869f10a25c83

That should do it.
