### ISSUE TITLE
high scores - by null

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#118]
I can't recall if this is one of those "one time script to clean it out" things. But right now existing high scores say "by null" instead of just not including that string (Note: not ALL of them say this; the new ones say "by ssw").

Just leaving this issue here in case it's a one-time script thing.

**Comment by scottwainstock** [comment]
@RyanTG I ran a script in STAGING to remove high scores that don't have users associated with them. I think that's how decided to handle that.

BUT... I don't think we want to delete all comments that don't have users associated with them, right? (that would effectively be removing all the comments) Do we break that work out in a separate item? I'd assume the work would be to correct all the pages that say "by null" and have it just not say "by" anything, right?

**Comment by RyanTG** [comment]
Yeah, we shouldn't delete comments. And yeah, if "by null" then don't display "by null."

What if someone makes their username "null"?😎 And can I type an emoticon in a GitHub comment?

**Comment by RyanTG** [comment]
This issue is unnecessary to include in pbm-android because of this one for the website: https://github.com/scottwainstock/pbm/issues/498
