### ISSUE TITLE
Remove name and email fields from Suggest a New Region form

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#119]
I tried to do this myself, but it resulted in the messages not going through (even though they said "success" in the app).

I did successfully remove those fields from the Contact Admin form (https://github.com/RyanTG/pbm-android/commit/7fb28cc5eb8a09bcccfe4d69369bcaaa04d9b99f). Not sure why it worked on that and not this one. It seems pretty straightforward. 

So perhaps there's something else along the way checking for name and email and rejecting if they aren't present.

**Comment by scottwainstock** [comment]
@RyanTG Did you just get a pbm-staging email with a region suggestion?

**Comment by RyanTG** [comment]
No. Did you send it to Portland?

**Comment by RyanTG** [comment]
Sorry, my reply made no sense.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/e63df5338d834210a4845d4ee2061eb02964d2c9

**Comment by scottwainstock** [comment]
@RyanTG b1dc100bed93581f4bd2726b1fce58c0205d8979

Should be good.

**Comment by RyanTG** [comment]
Thanks!
