### ISSUE TITLE
Initial loading time

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#121]
Compared with other apps, ours seems to take a long time to load when you first start it. Sometimes it takes 15-20 seconds. I know we've talked about this before, but is there anything that can be done to shorten it? Like, can some data be loaded "asynchronously" while the app is running (such as the FULL list of machines that is used for adding machines to a location?).

Once it loads, it's very smooth. I just think that initial load is super long (even at home on wifi). We can talk about this in our call.

**Comment by RyanTG** [comment]
Not sure if our dev builds have debugging turned on. If so, that could be a factor.

**Comment by scottwainstock** [comment]
It's possible that SOME of this is the staging site spinning up when it's
been idle for a while.

Do you see similar load issues in the live app against the live site?

**Comment by RyanTG** [comment]
Not sure, because I haven't used the live app in a while (latest dev build is installed on my phone, and as far as I can tell I can't have both). But yeah, that sounds logical.

I was going to check out the method tracer tool tomorrow.

Here are some links I found:
http://stackoverflow.com/questions/38475179/android-app-slow-initial-startup-time

https://developer.android.com/topic/performance/launch-time.html#internals
