### ISSUE TITLE
Profile page - include text "None yet" when no locations edited or high scores

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#123]
If no high scores have been added or locations edited, the Locations Edited and High Scores sections are blank. Can you add placeholder text that says, "None yet"? Similar to how location_machine_edit says "No conditions" when there aren't any. 

I couldn't figure out how to add this to the java. I see how it's done for location_machine_edit.java, but I can't quite translate that to profile.java.

**Comment by RyanTG** [comment]
I also want to add: when you load the profile page, it jumps down to the list of locations edited (kind of like when you load a page with an anchored link). Maybe the nonscrolllistview is doing this?

**Comment by scottwainstock** [comment]
@RyanTG 1a98f58f15487b354c7e12b906aa863a6aaa3a9a That should handle it.

**Comment by RyanTG** [comment]
Thanks! I think that will be the last of my android  requests.
