### ISSUE TITLE
Distance not always showing up on Profile page

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#127]
I've noticed that the list of Locations Edited often does not show the distance. But I can fix it by going to Closest Locations, and then back to the Profile.

Steps to reproduce:
Open app. 
Go to Profile. No distance listed for the locations edited.
Go to "Closest Locations" (distance will be listed for the closest locations)
Then go back to profile, and now the distance IS listed for the locations edited.

Could be something with my phone. Or it's that my location hasn't been requested from the app yet when I first go to Profile.

**Comment by RyanTG** [comment]
Tagging this as "auth required" because it seems legit and I dunno how to fix it myself (can't figure out what code checks for location).

**Comment by scottwainstock** [comment]
@RyanTG This should cover it: https://github.com/scottwainstock/pbm-android/commit/2685188f9dab2c402e306bc4a67f2ef5f1d69cdc

**Comment by RyanTG** [comment]
It's crashing in the emulator (api 22). I don't think my emulated device has location services on - or something like that - because when I bring up the list of locations, the distance is not displayed under each one.

When I click profile, it crashes:

E/AndroidRuntime: FATAL EXCEPTION: Thread-234
                  Process: com.pbm, PID: 4752
                  java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.distanceTo(android.location.Location)' on a null object reference
                      at com.pbm.Location.setDistance(Location.java:66)
                      at com.pbm.Profile.getProfileData(Profile.java:166)
                      at com.pbm.Profile$2.run(Profile.java:72)
                      at java.lang.Thread.run(Thread.java:818)
