### ISSUE TITLE
Crashing when location settings are off

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#132]
This is related to the closed issue: https://github.com/scottwainstock/pbm-android/issues/128 and picks up where https://github.com/localh0rzd/pbm-android/commit/623ef9a8304a55b39137ea9bd93f1de1ae0fc106 left off.

**Two types of potential situations:** 
1. Location permission is ACCEPTED, but the phone's location services are turned OFF.
2. Location permission is DENIED.

**How the app currently behaves under situation 1:**

_Good:_ 
- The list of locations loads (but with no distance), as do all the other "lookup by" pages.
- Location details load.

_Bad:_
- The profile page crashes the app. (EDIT: seems fixed with this https://github.com/scottwainstock/pbm-android/pull/131/commits/d11830cef0a9fad29de4593659fa2bd27aef3d8e)
- Map crashes the app.
- Closest Locations just shows the locations in alpha order. I guess we could add something here that suggests the user turn on location services?

_Fine:_
- Change Region. The "by distance" list shows the locations in alpha order. Seems fine.

**How the app currently behaves under situation 2:**

Dunno yet. I'll fill this in later.

**Comment by RyanTG** [comment]
I think I fixed the profile page crash. https://github.com/scottwainstock/pbm-android/pull/131/commits/d11830cef0a9fad29de4593659fa2bd27aef3d8e

Just added an IF that checks for location services. Tested on my phone with GPS off and then on, and it worked fine.

**Comment by scottwainstock** [comment]
Does it work....COARSE? (lol)

**Comment by RyanTG** [comment]
Looks like it does not. COARSE = wifi and cell towers, right? The page doesn't crash, but the distance isn't there.

**Comment by scottwainstock** [comment]
Yeah, pretty sure that's what COARSE is. Did Andrej's stuff ask you to
enable COARSE, or just FINE?

**Comment by RyanTG** [comment]
I don't remember. 

Maybe I should have done something closer to this: http://stackoverflow.com/a/27570700

Because I was getting stuck on doing something like: if ( lm.isProviderEnabled( LocationManager.GPS_PROVIDER OR LocationManager.NETWORK_PROVIDER) ){

Not sure what the correct operator syntax is in that context.

I'll work on it more, but I have to run right now.

Also, I don't think I have a clue what to do about getting the MAP not to crash the app.

**Comment by scottwainstock** [comment]
I think we just disable the map if they don't have the permission
enabled.... we don't show the little icon.

**Comment by RyanTG** [comment]
I guess so. Too bad we can't just show the pins for the locations, and not worry about the user's current location.

**Comment by scottwainstock** [comment]
Oh yeah good point. I bet that's possible... just need to add some ifs in
the map code.

**Comment by RyanTG** [comment]
Support for coarse location on the profile page: https://github.com/scottwainstock/pbm-android/pull/131/commits/05f44d103d44a52ad5245e069ea3abde8da7eb3e

I just made two separate IF statements. Seems to work fine.

And, Andrej's commit requests FINE location (based on what I see in the code), but with coarse location enabled on my phone, I still see the distance on the location list.

**Comment by RyanTG** [comment]
And feel free to scrap my update here, in case it's not sophisticated enough (perhaps it should also be offering another permission request?).

On the map code, we have googleMap.setMyLocationEnabled(true); and AS gives a warning that we should be checking/requesting that permission. My basic check doesn't cut here. So I'll leave that section up to you. I wish I could figure it out!

**Comment by RyanTG** [comment]
On the current beta, the map crashes if you pull up multiple locations. Once my latest commits are merged and moved to beta, I'll test it again.
