### ISSUE TITLE
Update store images when auth_required app is released.

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#134]
[pbm-android-assets-3.0-BETA.zip](https://github.com/scottwainstock/pbm-android/files/602380/pbm-android-assets-3.0-BETA.zip) (don't use this zip - sez ryan)

**Comment by RyanTG** [comment]
Zip containing final draft of screenshots. And the store launcher icon.

[pbm-android-assets-3.0-final.zip](https://github.com/scottwainstock/pbm-android/files/615150/pbm-android-assets-3.0-final.zip)
![ic_launcher-web](https://cloud.githubusercontent.com/assets/632682/20652970/693d867c-b4b9-11e6-8690-01f0ece80cf0.png)

**Comment by RyanTG** [comment]
Also include:
Promo Graphic
Default – English (United States) – en-US
180 w x 120 h
JPG or 24-bit PNG (no alpha)

Feature Graphic 
Default – English (United States) – en-US
1024 w x 500 h
JPG or 24-bit PNG (no alpha)

Not really sure what to update them to. But I'll work on it.

**Comment by scottwainstock** [comment]
@RyanTG Added.
