### ISSUE TITLE
Bug: All locations showing they were updated today (android only)

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#138]
ALL of the locations are saying they were last updated today (some by tzr, some by ssw, some by no user).

On the iOS app and website, this is not the case (the dates are not all today). So this seems limited to android.

(I made a new issue - I don't want things to get lost in that bug squash issue).

**Comment by scottwainstock** [comment]
This looks like maybe a copy/paste error:
https://github.com/scottwainstock/pbm-android/commit/00794eddda10aae693c5b35dfa0f9fcf9c749add
