### ISSUE TITLE
Prevent disabled user from logging in (with error message)

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#140]
Could this be done server side? If a user is disabled (which may be defined as "inactive" right?), they can't login, and will receive a message saying, "Your account is disabled. Please contact us if you think this is a mistake."

**_Just some details about what I tried:_**

Steps:
I logged in as a user and made an edit. 
Then I closed the app.
Then in admin I disabled that user.

When I reopened the app, I was still logged in as that user, but didn't have access to any data. Might be nice to get a message or something.

Once I logged out, and continued as guest: 
I found that the last location this locations details did not say "updated by this user" but instead it showed "updated by the last user." 

After logging out, I can still log back in as the disabled user. However, I don't have any access to data.

One interesting thing is that the lookup screens are different. When the disabled user is logged in, the lookup screen is missing lookup by Zone and lookup by Operator (I think both of these were lookups were recently added to the app).

**Solutions:** 
1) We should prevent the disabled user from logging in (but note: if they reopen the app after closing it while logged in, they'll automatically be logged in - so we'd have to force them out). And **We show them a message saying their account has been disabled.**
_or_
2) We do nothing. They are dead to us. Let them suffer.

**Comment by RyanTG** [comment]
Note that none of my recent commits relating to unconfirmed users applies to disabled users. I think disabled users are in a different category: inactive. Right?

**Comment by scottwainstock** [comment]
@RyanTG This should now be handled with server-side code.

**Comment by RyanTG** [comment]
Confirmed.
