### ISSUE TITLE
Upgrade target API to 25

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#149]
Resolve `java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 598240 bytes` error.

See our previous conversation about this: https://github.com/scottwainstock/pbm-android/issues/136

This will hopefully speed up the initial loading time. Maybe not... but it would be cool if it does.

**Comment by RyanTG** [comment]
Could this be resolved with some sort of pagination of results? Like, only load 15 results at a time? Pagination would make sense for locations, but not for the list of machines in a region (I can't remember if the error occurs when loading the "sort by machines" list).

**Comment by scottwainstock** [comment]
https://stackoverflow.com/questions/43466445/transactiontoolargeexception-only-on-nougat

**Comment by scottwainstock** [comment]
Think I finally have my brain around this now... definitely see where the problem starts:
https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/PinballMapActivity.java#L63

I think the answer here is going to be tossing everything in a SQLite database. It's a big change, but will hopefully end up being mostly grunt work. I'm hopeful it'll speed thing up in the app.

**Comment by scottwainstock** [comment]
@RyanTG FYI, I just pushed some code that breaks the build... I wanted to get a save point for the SQLite conversion out. After I pushed it, it occurred to me that this might screw YOU up. Sorry. Hopefully you aren't planning on touching any of the Android code for a bit. I'l hopefully have it in a buildable state soon.

**Comment by RyanTG** [comment]
K. It's cool - I just won't pull from you if I do anything (I'd probably be touching different stuff, so maybe that's ok). Plus I don't _have_ to do anything!

**Comment by scottwainstock** [comment]
Got this handled with the move to SQLite.

**Comment by scottwainstock** [comment]
@RyanTG Unless you have strong objections, I want to move our minimum API requirement to 19. We're at 15 right now. 19 is the minimum API still supported by Google, and past 16 we get some performance boosts and SQLite features I want to use. What do you think?

https://en.wikipedia.org/wiki/Android_version_history

**Comment by RyanTG** [comment]
I'm cool with that.

**Comment by scottwainstock** [comment]
@RyanTG You want this test build to point to staging or live?

**Comment by RyanTG** [comment]
Staging. The better to fuck with it.

**Comment by scottwainstock** [comment]
@RyanTG http://scottwainstock.com/app-release.apk

This should fix the "quit multiple times" bug, ups our API target, new SQLite backend, SLIGHTLY faster loading time?

I'm going to focus on the loading time now.

This points to staging.

**Comment by RyanTG** [comment]
When I try to install it, it fails for an unknown reason. "App not installed."

Can I just pull it from github and install it through android studio?

**Comment by RyanTG** [comment]
So the permission to use "Storage" is new, right? And that's necessary for the sqlite stuff to work?

I didn't get a prompt to allow the permission. But I'll test it some more.
