### ISSUE TITLE
Editing location metadata doesn't refresh the "last updated..." date

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#152]
From my testing: editing location info doesn't always update the "last updated" date (for example, adding a new phone number doesn't cause the date to update). BUT ONLY IN THE APP. If you make this edit on the app, the website will correctly display a new "last updated" date. You'll also see the correct date if you restart the app.

So the issue seems to be that the date display isn't refreshing on the app.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/821ca118f130cc7fd64d20f0b800bb8ac2c7afdf
