### ISSUE TITLE
speed up app loading time

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#156]
With live data: When not on wifi, it takes 30 seconds to 1 minute to first load the app. Changing a region takes around 10 seconds before the list of regions is displayed.

**Comment by scottwainstock** [comment]
We're loading all the data twice.

**Comment by RyanTG** [comment]
D'oh. Hope I didn't accidentally make that happen.

**Comment by scottwainstock** [comment]
N, this has been in here for a while.

**Comment by scottwainstock** [comment]
It's likely the same issue that's causing us to have to quit multiple times.

**Comment by RyanTG** [comment]
Just noting, I don't think the initial load time decreased in the latest build. On WiFi, it takes about 40 seconds to load Portland. 30 seconds to load Los Angeles.

**Comment by scottwainstock** [comment]
Speed to pull down data in staging:
10-23 20:02:40.280 13853-13922/com.pbm D/com.pbm: STARTING LOCATION LOAD
10-23 20:02:42.160 13853-13922/com.pbm D/com.pbm: ENDED LOCATION LOAD

**Comment by scottwainstock** [comment]
@RyanTG Just pushed a db caching speed-up... dropped dev load time from 17 seconds to 10 seconds. I'll keep looking for more, but I wanted to let you know.

**Comment by RyanTG** [comment]
Sweet! 

Maybe I should stop testing on my phone, but instead test in the AS emulator. Because things seem different on my phone. For example, on my phone if a location has 7 machines, the list of locations (aka lookup by location) will say 14. But it's not doing this in the emulator. I don't know why it would be messed up on my phone. It's annoying.

**Comment by RyanTG** [comment]
I'm getting 16 seconds, loading Portland, in live (on wifi). This is using the emulator.

`10-23 21:17:26.604 2819-2819/com.pbm D/com.pbm ELAPSED TIME: 16056`

Right? Looks like 16 seconds. Am I looking at the right thing?

And if I push the build to my phone, I get this crap:

`10-23 21:24:49.780 10110-10110/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
10-23 21:24:50.048 10110-10110/com.pbm D/com.pbm ELAPSED TIME: 40033`

40 seconds? Why does my phone suck.

**Comment by scottwainstock** [comment]
That log entry isn't an indication of total time to load the app. It's an old debug statement that I left in after fixing the double load issue.

https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/PinballMapActivity.java#L136

If you want to see total time from start to "ready"... do the time difference between 
STARTING APP???????????
And...
LOADED MENU!!!!!

**Comment by RyanTG** [comment]
10-23 22:57:26.241 10145-10145/com.pbm D/com.pbm: STARTING APP???????????
10-23 22:58:10.532 10145-10145/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!

44 seconds. This is going from a totally closed app (where the previous state was the portland menu), and then opening it. 

"verbose" log doesn't give a whole lot of details.

**Comment by scottwainstock** [comment]
https://stackoverflow.com/questions/6236340/how-to-limit-speed-of-internet-connection-on-android-emulator

I'll start working this way.

**Comment by RyanTG** [comment]
Do you know why it would be so much slower on my phones vs in AS, given that all are using wifi on the same network?

I flailed last night in AS. Couldn't accomplish anything.

**Comment by scottwainstock** [comment]
No idea... first step would be timing how long each of the "load" steps
take. I have some debug statements that say when each piece (e.g. regions,
locations, machines) start/stop.

**Comment by scottwainstock** [comment]
The idea being to find out if the issue is network based or processing
based.

On Tue, Oct 24, 2017 at 10:08 AM, Scott Wainstock <scott.wainstock@gmail.com

**Comment by RyanTG** [comment]
Oh yeah, I noticed that and should have included each step in my c/p above.

**Comment by scottwainstock** [comment]
Locations (the slowest part of the pull) is only 777k for Portland... I feel like phones handle images in webpages that are much larger than this.

**Comment by scottwainstock** [comment]
Dropping machines and machine conditions from the locations endpoint takes it down to 135k.

**Comment by RyanTG** [comment]
Yeah, 777k doesn't seem overly giant.

**Comment by scottwainstock** [comment]
@RyanTG When you get a second... can you pull from master, point it to staging, and let me know how the performance is? I think I'm seeing a speed-up on load time, but I want to confirm.

This change BREAKS the app beyond the initial loading page. Fixing it further shouldn't be too hard.

**Comment by RyanTG** [comment]
**Staging. Before pulling. On device. Loading Portland.**
````
10-28 15:33:22.897 29613-29613/com.pbm D/com.pbm: STARTING APP???????????

10-28 15:33:26.583 29613-29751/com.pbm D/com.pbm: TIMING STARTING REGION
10-28 15:33:28.473 29613-29751/com.pbm D/com.pbm: TIMING STARTING MACHINES
10-28 15:33:33.569 29613-29751/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
10-28 15:33:47.208 29613-29751/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
10-28 15:33:47.659 29613-29751/com.pbm D/com.pbm: TIMING STARTING ZONES
10-28 15:33:47.958 29613-29751/com.pbm D/com.pbm: TIMING STARTING OPERATORS
10-28 15:33:48.149 29613-29751/com.pbm D/com.pbm: TIMING STARTING MACHINE SCORES

10-28 15:33:49.350 29613-29613/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
27 seconds.

**Same thing, again:**

````
10-28 15:37:32.396 770-770/com.pbm D/com.pbm: STARTING APP???????????

10-28 15:37:36.995 770-965/com.pbm D/com.pbm: TIMING STARTING REGION
10-28 15:37:38.708 770-965/com.pbm D/com.pbm: TIMING STARTING MACHINES
10-28 15:37:47.202 770-965/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
10-28 15:38:03.222 770-965/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
10-28 15:38:03.975 770-965/com.pbm D/com.pbm: TIMING STARTING ZONES
10-28 15:38:04.273 770-965/com.pbm D/com.pbm: TIMING STARTING OPERATORS
10-28 15:38:04.523 770-965/com.pbm D/com.pbm: TIMING STARTING MACHINE SCORES

10-28 15:38:05.704 770-770/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
33 seconds. [FULL LOG](https://gist.github.com/RyanTG/0110ba9d07e9eb9ae200dcd3269fd2ab). A lot of that log is just my phone doing dumb shit... Why does it look up "Broth" - which is a chromecast I've connected it to (that isn't even on right now)?

**Staging. AFTER pulling. On device. Loading Portland.**

````
10-28 15:44:05.505 7482-7482/com.pbm D/com.pbm: STARTING APP???????????

10-28 15:44:09.695 7482-7626/com.pbm D/com.pbm: TIMING STARTING REGION
10-28 15:44:11.539 7482-7626/com.pbm D/com.pbm: TIMING STARTING MACHINES
10-28 15:44:16.240 7482-7626/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
10-28 15:44:19.233 7482-7626/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
10-28 15:44:19.834 7482-7626/com.pbm D/com.pbm: TIMING STARTING ZONES
10-28 15:44:20.191 7482-7626/com.pbm D/com.pbm: TIMING STARTING OPERATORS
10-28 15:44:20.448 7482-7626/com.pbm D/com.pbm: TIMING STARTING MACHINE SCORES

10-28 15:44:21.774 7482-7482/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````

16 seconds. [FULL LOG](https://gist.github.com/RyanTG/296ae3764144728f9773c300477edfbe).

**Comment by scottwainstock** [comment]
@RyanTG Can you do another pull and try one more time, please? I dropped score loading, and slimmed down the size of the Machine json INDEX endpoint. I'll start making things actually work beyond the main menu.

**Comment by RyanTG** [comment]
````
10-29 08:57:10.584 13702-13702/com.pbm D/com.pbm: STARTING APP???????????

10-29 08:57:13.943 13702-13820/com.pbm D/com.pbm: TIMING STARTING REGION
10-29 08:57:15.912 13702-13820/com.pbm D/com.pbm: TIMING STARTING MACHINES
10-29 08:57:20.481 13702-13820/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
10-29 08:57:23.362 13702-13820/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
10-29 08:57:23.758 13702-13820/com.pbm D/com.pbm: TIMING STARTING ZONES
10-29 08:57:23.986 13702-13820/com.pbm D/com.pbm: TIMING STARTING OPERATORS

10-29 08:57:24.289 13702-13702/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
14 seconds.

Take 2.

````
10-29 09:00:06.114 15699-15699/com.pbm D/com.pbm: STARTING APP???????????

10-29 09:00:09.853 15699-15836/com.pbm D/com.pbm: TIMING STARTING REGION
10-29 09:00:11.624 15699-15836/com.pbm D/com.pbm: TIMING STARTING MACHINES
10-29 09:00:16.674 15699-15836/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
10-29 09:00:19.587 15699-15836/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
10-29 09:00:20.035 15699-15836/com.pbm D/com.pbm: TIMING STARTING ZONES
10-29 09:00:20.305 15699-15836/com.pbm D/com.pbm: TIMING STARTING OPERATORS

10-29 09:00:20.626 15699-15699/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````

14 seconds.

Pretty zippy!

**Comment by scottwainstock** [comment]
@RyanTG If you pull from master, I *think* you should have a 100% functional app. I'm still QA, but let me know if you see crashes.

I added a loading indicator to the high scores and recent machines pages... those were taking a little bit to load. Let me know what you think about that whole flow.

**Comment by RyanTG** [comment]
Cool! I'll install it.

I got a gradle fail right now, but I think it's related to my android studio being version 2.3.3. So I'm updating it to 3.

Is this necessary for this version? https://github.com/scottwainstock/pbm-android/issues/162

**Comment by scottwainstock** [comment]
I can take care of that one, yeah. I always want to do a few more speedup passes.

**Comment by RyanTG** [comment]
I'm getting a grip of errors related to `...19:26.402 16695-16751/com.pbm E/SQLiteLog: (1) table locations has no column named num_machines`

And then the app crashes. I'm using the staging site.

**Comment by RyanTG** [comment]
Full error:

````
11-04 14:26:22.103 2540-2638/com.pbm E/SQLiteLog: (1) table locations has no column named num_machines
11-04 14:26:22.103 2540-2638/com.pbm E/SQLiteDatabase: Error inserting distance_from_you=0.0 lon=-124.0119315 zone_id=102 operator_id=0 website= city=Lincoln City phone=(541) 994-8515 state=OR num_machines=2 date_last_updated=01/16/2017 location_type_id=14 miles_info=null street=1604 U.S. 101 description= id=4464 name=Old Oregon Tavern last_updated_by_username=ssw zip=97367 lat=44.9765046
                                                       android.database.sqlite.SQLiteException: table locations has no column named num_machines (code 1): , while compiling: INSERT INTO locations(distance_from_you,lon,zone_id,operator_id,website,city,phone,state,num_machines,date_last_updated,location_type_id,miles_info,street,description,id,name,last_updated_by_username,zip,lat) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                           at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                           at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
                                                           at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
                                                           at com.pbm.PBMApplication.addLocation(PBMApplication.java:435)
                                                           at com.pbm.PBMApplication.initializeLocations(PBMApplication.java:1126)
                                                           at com.pbm.PBMApplication.initializeData(PBMApplication.java:767)
                                                           at com.pbm.InitializingScreen$SplashThread.run(InitializingScreen.java:35)````

And it repeats this for every location.

**Comment by scottwainstock** [comment]
Yeah you should uninstall the entire app and reinstall. That should clear
it.

**Comment by RyanTG** [comment]
I can't only get it to run on the api 22 emulator. When I install it on my phone, I think it's trying to load a region immediately (rather than the login screen), and that's where the problem occurs.

Dunno why uninstalling isn't clearing those settings.

**Comment by RyanTG** [comment]
Uninstalling app and then restarting my phone fixed this issue.

This is cool! I'll keep QAing, but so far it looks great. I like the loading indicator.

**Comment by RyanTG** [comment]
Issue: lookup by machine. When you click on a machine name, most of the time it doesn't list which location the machine is at. Only occasionally does it list a location (in fact, in portland I couldn't find one instance of the location being listed, but in LA I found a couple). Not sure if this is a staging-related issue.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/c37ae7494cfe34e62851275f76c08808173c8878

**Comment by scottwainstock** [comment]
@RyanTG Can you pull master and let me know how your timing looks? I switched the major json parsing over to Jackson. Performance seems pretty much the same on my machine, but it's a laptop.

**Comment by RyanTG** [comment]
K.

````
11-05 22:42:06.985 11039-11039/com.pbm D/com.pbm: STARTING APP???????????

11-05 22:42:09.773 11039-11513/com.pbm D/com.pbm: TIMING STARTING REGION
11-05 22:42:10.748 11039-11513/com.pbm D/com.pbm: TIMING STARTING MACHINES
11-05 22:42:14.917 11039-11513/com.pbm D/com.pbm: TIMING STARTING TAG REGION MACHINES
11-05 22:42:15.303 11039-11513/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
11-05 22:42:18.347 11039-11513/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
11-05 22:42:18.804 11039-11513/com.pbm D/com.pbm: TIMING STARTING ZONES
11-05 22:42:19.062 11039-11513/com.pbm D/com.pbm: TIMING STARTING OPERATORS

11-05 22:42:19.320 11039-11039/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````

13 seconds.

Trying again:

````
11-05 22:45:18.736 12952-12952/com.pbm D/com.pbm: STARTING APP???????????
11-05 22:45:36.340 12952-12952/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
16 seconds. 

So, it seems the same =/

**Comment by scottwainstock** [comment]
@RyanTG One more pull/try, please. I dropped some fields from the download and I used a different loading technique with Jackson. This build has a lot of broken features, but I'm curious how the timing looks.

**Comment by RyanTG** [comment]
````
11-06 21:44:20.126 10564-10564/com.pbm D/com.pbm: STARTING APP???????????

11-06 21:44:23.484 10564-10628/com.pbm D/com.pbm: TIMING STARTING REGION
11-06 21:44:25.294 10564-10628/com.pbm D/com.pbm: TIMING STARTING MACHINES
11-06 21:44:31.678 10564-10628/com.pbm D/com.pbm: TIMING STARTING TAG REGION MACHINES
11-06 21:44:32.040 10564-10628/com.pbm D/com.pbm: TIMING STARTING LOCATIONS
11-06 21:44:35.696 10564-10628/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
11-06 21:44:36.177 10564-10628/com.pbm D/com.pbm: TIMING STARTING ZONES
11-06 21:44:36.512 10564-10628/com.pbm D/com.pbm: TIMING STARTING OPERATORS

11-06 21:44:36.932 10564-10564/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
16 seconds.

2nd try:

````
11-06 21:46:17.345 11107-11107/com.pbm D/com.pbm: STARTING APP???????????
11-06 21:46:39.610 11107-11107/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````
22 seconds!

**Comment by scottwainstock** [comment]
Super super weird... this is considerably less data.

**Comment by RyanTG** [comment]
I tried two more times, and they were 22 and 21 seconds. At first I thought it might have been slow because I had just restarted the phone, and had opened and then completely closed the app. But it's pretty consistent.

Yeah, that is weird!

**Comment by scottwainstock** [comment]
@RyanTG OK how about NOW? I moved location/machine loading to a separate background thread. There are surely all kinds of bugs/issues with the app right now, but they are fixable.

**Comment by RyanTG** [comment]
````
11-07 20:34:28.751 27251-27251/com.pbm D/com.pbm: STARTING APP???????????

11-07 20:34:32.469 27251-27317/com.pbm D/com.pbm: TIMING STARTING MACHINES
11-07 20:34:32.726 27251-27319/com.pbm D/com.pbm: TIMING STARTING REGION
11-07 20:34:34.384 27251-27319/com.pbm D/com.pbm: TIMING STARTING LOCATION TYPES
11-07 20:34:35.020 27251-27319/com.pbm D/com.pbm: TIMING STARTING ZONES
11-07 20:34:35.351 27251-27319/com.pbm D/com.pbm: TIMING STARTING OPERATORS
11-07 20:34:39.215 27251-27317/com.pbm D/com.pbm: TIMING STARTING TAG REGION MACHINES
11-07 20:34:39.557 27251-27317/com.pbm D/com.pbm: TIMING STARTING LOCATIONS

11-07 20:34:35.712 27251-27251/com.pbm D/com.pbm: LOADED MENU!!!!!!!!!!!!!
````

7 seconds!

**Comment by scottwainstock** [comment]
@RyanTG The 4 seconds between "STARTING APP" and the first timings is kind of interesting to me. I'll see what might be going on in there.

**Comment by RyanTG** [comment]
Full log starting when (or near when) I clicked the launch button:
https://gist.github.com/RyanTG/32bc6f385309548d66c3f54b6b9f912d
But I guess you can see this yourself in AS.

Lotta crap from my phone in there. But maybe some of it is useful.

**Comment by scottwainstock** [comment]
@RyanTG Give it another shot, please. The logcat thing that I'm interested in seeing looks like this:
11-09 21:45:10.492 1580-1603/system_process I/ActivityManager: Displayed com.pbm/.PBMMenu: +471ms (total +3s567ms)

...that's the total time it takes to load the menu and make the app interactive.

Another thing I'm interested in hearing about... as SOON as you see the menu, touch lookup by location or by machine or by zone or by type or by city. Right now I have those pages spin until ALL the data is loaded in the background.

My hunch is that your menu will load quick-ish (hopefully 3-4 seconds), but it'll take ~15 seconds to get data back after you click a menu item. If that's the case, I can try and make these smarter so that they don't wait for ALL data to load, just the data they need to operate. It gets trickier and more bug prone if we need to do that though.

The data starts loading up in the background shortly before you see the menu. So if you were to just sit and stare at the main menu for ~15 seconds or however long this takes you... it should load all sub menus immediately after you touch them.

App is pretty broken, I'm still working on the loading stuff.

**Comment by RyanTG** [comment]
That's interesting. I'll give it a looksee.

**Comment by RyanTG** [comment]
Various goes at it:

````
11-09 22:15:25.719 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +407ms (total +6s117ms)
11-09 22:17:53.600 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +395ms (total +43s574ms)
11-09 22:18:01.464 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +198ms
11-09 22:18:06.860 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +209ms
11-09 22:18:09.298 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +218ms
11-09 22:18:11.608 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +219ms
11-09 22:18:19.059 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +253ms
11-09 22:20:25.587 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +361ms (total +14s920ms)
11-09 22:21:15.599 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +408ms (total +15s410ms)
11-09 22:21:27.752 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +204ms
11-09 22:21:55.089 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +374ms (total +16s169ms)
11-09 22:22:03.118 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +235ms
11-09 22:22:06.727 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +184ms
11-09 22:22:09.227 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +173ms
11-09 22:22:11.417 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +197ms
11-09 22:22:13.524 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +207ms
11-09 22:22:15.391 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +157ms
11-09 22:22:26.672 2517-2592/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +171ms
````

BUT, I counted to myself alongside those entries that are like `14s920ms` and they were NOT really 14 seconds! I'd click the button and count to 7 or 8, and the log would say 15. 

The other entries are me clicking "Lookup by...". Overall, not much of a lag. If the first thing I clicked was Lookup by Location, then it loaded right away (one time it loaded right away but only six locations were listed). If the first thing I clicked was Lookup by Machine, then it takes a good 8 more seconds to load (I replicated this). Going back to: If the first thing I clicked was Lookup by Location, it loaded right away, and then if I cycled down the rest of the list, all of the others loaded immediately. And I didn't linger on the Lookup by Location results. 

Note that Lookup by Operator and Lookup by Location Type didn't load anything ever. But probably just a bug.

**Comment by RyanTG** [comment]
````
11-17 11:13:29.135 18696-18696/com.pbm D/com.pbm: TIMING STARTING REGION
11-17 11:13:34.235 18696-18696/com.pbm D/com.pbm: TIMING ENDING REGION
11-17 11:13:34.242 18696-18821/com.pbm D/com.pbm: TIMING STARTING MACHINES
11-17 11:13:34.245 18696-18824/com.pbm D/com.pbm: TIMING STARTING ZONES
11-17 11:13:34.246 18696-18823/com.pbm D/com.pbm: TIMING STARTING LOCATION, LOCATION TYPES, OPERATORS
11-17 11:13:35.452 18696-18824/com.pbm D/com.pbm: TIMING ENDING ZONES
11-17 11:13:41.213 18696-18821/com.pbm D/com.pbm: TIMING ENDING MACHINES
11-17 11:13:43.925 18696-18823/com.pbm D/com.pbm: TIMING ENDING LOCATION, LOCATION TYPES, OPERATORS
````

**Comment by RyanTG** [comment]
I know events aren't loading right now, but I just wondered if those might be too slow, too. In Portland there are tons of events, and they are listed like a year in advance.

**Comment by scottwainstock** [comment]
@RyanTG Are events slow on the live build right now? I want to set this thing to "pending review", events would be the last bit I want to look at if they are currently slow.

**Comment by RyanTG** [comment]
Events are not slow to load on the live app.
