### ISSUE TITLE
Change Event date format

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#157]
Change to Mon 01, 2017

**Comment by scottwainstock** [comment]
@RyanTG What about the month?

**Comment by RyanTG** [comment]
My bad. Let's just have it be consistent with the other dates on the site.

So: 01/04/2018

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/9b0346ee91d721095aa97b631957e6a1da3edaf6
