### ISSUE TITLE
Need to request Storage permission

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#162]
The sqlite stuff doesn't work without the user granting the Storage permission.

Why is requesting permission such a pain in the ass! There are like 18 different ways to do it. For example, we request location in a number of different places (except not on the region select page, oops), and each time it's different.

**Comment by scottwainstock** [comment]
@RyanTG What version of Android are you running?

https://developer.android.com/guide/topics/data/data-storage.html#db
```Beginning with Android 4.4, reading or writing files in your app's private directories does not require the READ_EXTERNAL_STORAGE or WRITE_EXTERNAL_STORAGE permissions. So you can declare the permission should be requested only on the lower versions of Android by adding the maxSdkVersion attribute.```

**Comment by RyanTG** [comment]
I'm running 6. I'll doublecheck the issue I thought I was seeing. I thought the log was showing me some "sqlite permission error" unless I manually toggled that permission on.

**Comment by RyanTG** [comment]
Thinking you're right. I don't see that sqlite permissions error anymore...

closing.
