### ISSUE TITLE
Can't touch location menu item until you scroll

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#164]
Check and see if this is on other menu items too.

**Comment by RyanTG** [comment]
What do you mean by location menu item? Like the menu that contains "change region" "contact admin" etc?

**Comment by scottwainstock** [comment]
Load app. Touch "lookup by location". Touch the first location. Nothing happens.

In the emulator...you have to scroll the list of locations before you can select one.

**Comment by RyanTG** [comment]
I can't replidouche this on my phone. I'm able to touch the first location without scrolling.

**Comment by scottwainstock** [comment]
OK, maybe just an emulator thing then.
