### ISSUE TITLE
Each time you load location details, the past machine comments seem to duplicate

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#178]
Steps:

- Click a location name.
- Click a machine at that location, so you can see the past machine comments (so, click one that has at least one comment).
- Go back to the Lookup by Location list
- Click that same location name
- Click that same machine

Result: 

The machine comment will be duplicated.

**Comment by scottwainstock** [comment]
I'm having trouble duplicating this!

**Comment by RyanTG** [comment]
I'll install a fresh build and test again.

**Comment by RyanTG** [comment]
Damn, still doing it for me. I uninstalled and reinstalled it on my phone.

**Comment by RyanTG** [comment]
![screenshot_20171213-093910](https://user-images.githubusercontent.com/632682/33953405-b358288c-dfe9-11e7-9a32-63f781013de8.png)

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/8daf5007cf0882904b23b013a1b467e1b0e382df

**Comment by scottwainstock** [comment]
@RyanTG OK well how about now?

**Comment by RyanTG** [comment]
I'm still experiencing the issue. I have another android phone - I'll load the app onto it just to doublecheck that it's not specific to my device.

**Comment by RyanTG** [comment]
Still there on phone #2.

**Comment by scottwainstock** [comment]
@RyanTG 
Can you put some debug statements in LocationMachineEdit... the loadConditions method?

I'm curious to see what the size of "ArrayList conditions" is for a specific location/machine.

**Comment by scottwainstock** [comment]
@RyanTG Preferable a location/machine that has more than 5 comments on it.

**Comment by RyanTG** [comment]
Sure, I can try.

Uh, how do I spit out `conditions.size` in a debug statement?
`Log.d("com.pbm", "NUM COMMENTS", conditions.size());` doesn't work. I can try to figure it out... but this is new to me.

**Comment by scottwainstock** [comment]
Log.d("com.pbm", "NUM COMMENTS: " + Integer.toString(conditions.size()));

**Comment by RyanTG** [comment]
This is a machine with 12 comments. Anything else I can do to make this more useful?

````
12-17 20:45:56.924 31502-31502/com.pbm D/com.pbm: location Machine edit resume
12-17 20:45:56.928 31502-31502/com.pbm D/com.pbm: timezone is libcore.util.ZoneInfo[id="America/Los_Angeles",mRawOffset=-28800000,mEarliestRawOffset=-28800000,mUseDst=true,mDstSavings=3600000,transitions=185]
12-17 20:45:56.928 31502-31502/com.pbm D/com.pbm: NUM COMMENTS: 12
12-17 20:45:56.934 31502-31502/com.pbm D/com.pbm: LOAD MACHINE CONDITIONS
12-17 20:45:56.934 31502-31502/com.pbm D/com.pbm: msx edit resume
12-17 20:45:56.936 31502-31502/com.pbm D/com.pbm: timezone is libcore.util.ZoneInfo[id="America/Los_Angeles",mRawOffset=-28800000,mEarliestRawOffset=-28800000,mUseDst=true,mDstSavings=3600000,transitions=185]
12-17 20:45:57.080 31502-31502/com.pbm D/com.pbm.location: PBM onConnected
12-17 20:46:05.830 31502-31502/com.pbm D/com.pbm.location: PBM onConnected
12-17 20:46:08.268 31502-31502/com.pbm D/com.pbm: ENABLING SPINNER
12-17 20:46:08.297 31502-31502/com.pbm D/com.pbm: DISABLING SPINNER
12-17 20:46:08.419 31502-31502/com.pbm D/com.pbm.location: PBM onConnected
12-17 20:46:09.760 31502-31502/com.pbm D/com.pbm: ENABLING SPINNER
12-17 20:46:09.953 31502-32005/com.pbm D/com.pbm: https://pinballmapstaging.herokuapp.com/api/v1/region/la/locations/4653.json?user_email=scott.wainstock@gmail.com;user_token=NCkxWks7jyeuidUrEMJx
12-17 20:46:10.271 31502-31502/com.pbm D/com.pbm: DISABLING SPINNER
12-17 20:46:10.286 31502-31502/com.pbm I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
12-17 20:46:10.362 31502-31502/com.pbm D/com.pbm.location: PBM onConnected
12-17 20:46:10.380 31502-31502/com.pbm W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
12-17 20:46:10.409 31502-31549/com.pbm D/OpenGLRenderer: endAllActiveAnimators on 0x61d40d00 (ListView) with handle 0xaf8d41d0
12-17 20:46:11.970 31502-31502/com.pbm D/com.pbm: location Machine edit resume
12-17 20:46:11.974 31502-31502/com.pbm D/com.pbm: timezone is libcore.util.ZoneInfo[id="America/Los_Angeles",mRawOffset=-28800000,mEarliestRawOffset=-28800000,mUseDst=true,mDstSavings=3600000,transitions=185]
12-17 20:46:11.974 31502-31502/com.pbm D/com.pbm: NUM COMMENTS: 24
12-17 20:46:11.979 31502-31502/com.pbm D/com.pbm: LOAD MACHINE CONDITIONS
12-17 20:46:11.979 31502-31502/com.pbm D/com.pbm: msx edit resume
12-17 20:46:11.981 31502-31502/com.pbm D/com.pbm: timezone is libcore.util.ZoneInfo[id="America/Los_Angeles",mRawOffset=-28800000,mEarliestRawOffset=-28800000,mUseDst=true,mDstSavings=3600000,transitions=185]
12-17 20:46:12.197 31502-31502/com.pbm D/com.pbm.location: PBM onConnected
````

**Comment by scottwainstock** [comment]
What's the location/machine name?

**Comment by RyanTG** [comment]
Region: Los Angeles
Location: 3.99 Pizza Company
Machine: Attack from Mars

**Comment by RyanTG** [comment]
Also, I can see this issue when I use the emulator. I'm using Nexus_5X_API25_x86

**Comment by scottwainstock** [comment]
Oh nice, thanks.

**Comment by scottwainstock** [comment]
haha, I still can't reproduce it... same everything.

BUT... I am seeing the number of conditions jump on the backend, even if
the front-end doesn't reflect this. So, I think I can fix the backend and
that'll fix your front-end.

**Comment by scottwainstock** [comment]
@RyanTG OK well maybe this fixed it. https://github.com/scottwainstock/pbm-android/commit/32370174592868e22b9656e9af0c567d81e13996

**Comment by RyanTG** [comment]
Fixed!
