### ISSUE TITLE
Machine comment date format

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#179]
Change from YYYY-MM-DD to MM/DD/YYYY

**Comment by RyanTG** [comment]
If you want to tend to this, go for it. I'll lagging tonight working on this postgres thing...

**Comment by scottwainstock** [comment]
Workin' on it.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/18250c59dd070b302438872cce8e99091a8f5834
