### ISSUE TITLE
Lookup by Machine results don't show distance

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#180]
Probably not a 4.0.1 issue. But I can try to take a look at it. Not sure if this issue exists on the live app, but I'll check.

If you click Lookup by Machine, and then you click a machine, it lists the locations that have that machine. But that list doesn't show the distance to that location.

**Comment by RyanTG** [comment]
Seems beyond me. All of the lookup lists seem to use LocationLookupDetail, except the lookup by machine uses https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/MachineLookupDetail.java. I'm having trouble getting that file to accept the distance code.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/1d201f82962ebaab454f74e0be138d8d654285d5

**Comment by RyanTG** [comment]
Damn man! I was _so_ close to getting that right :<
