### ISSUE TITLE
App "freezes OS" when loading

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#184]
Bring back the splash.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/4c3da5133ef390a61c6a7587a5e4873c07128a6d

@RyanTG Can you pull this and let me know what you think? We have a SPLASH screen... and then a loading screen. So, I left one with the little pinball icon, and made a "loading splash screen" that has the larger logo image.

**Comment by RyanTG** [comment]
Seems good. This is basically what we had before, before I tried to remove one of them and just show the larger logo as a full screen. So this moves us back to showing the larger logo as a not-quite-full screen. And I don't mind it at all! 

And yes, the app seems to load up immediately.

I made a background color adjustment https://github.com/scottwainstock/pbm-android/compare/master...RyanTG:master so it matches the logo.
