### ISSUE TITLE
Machine info

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#22]
When you're looking at the machines that are listed under a location.

Currently, when you click on a machine name, it shows you the condition comment, and that's it.

What about:

Machines Condition (and it would be nice to get rid of the fixed-height box that's currently there)
High Scores
Add Your Score
Other Locations (a link that when clicked shows which other locations have that machine)

I could try to mock up some screenshots for how I'm envisioning this.

**Comment by scottwainstock** [comment]
Gimme those screenshots.

**Comment by RyanTG** [comment]
I'll work on them.

**Comment by RyanTG** [comment]
Note to self: include pintips link, too.

**Comment by RyanTG** [comment]
![location_info](https://cloud.githubusercontent.com/assets/632682/17072229/a0057956-501b-11e6-855e-ccd696bf35ab.png)

Very rough screenshot (sorry, I suck at GIMP). Let me know if you have any questions. I think it would be sweet if the remove button at the bottom was ALWAYS visible on the page, even if the contents of the page have to scroll. And the high score list should look similar to the comments list. Also, I don't think we need to include Rank on the scores. But it would be cool if they are in ascending order and only the top 5 show up.

**Comment by RyanTG** [comment]
the pintips link is http://pintips.net/pinmap/machine/{machine_id}
OR
http://pintips.net/pinmap/group/{group_id}
If that machine is part of a group.

**Comment by scottwainstock** [comment]
pintips and other locations: 44430fd1b859393285221ae117ce08298fddd915

**Comment by scottwainstock** [comment]
only show last 5 conditions: commit/255c9ea405b3d8f4ef36d85c4d022710814baed1

**Comment by scottwainstock** [comment]
@RyanTG Can you take a look at this when you get a second? I need to add the high scores, but I think we ran out of real estate.

**Comment by RyanTG** [comment]
Yes, will do tomorrow. It's ok if the page scrolls, right?

**Comment by scottwainstock** [comment]
Oh yeah, uhhh... somehow forgot that pages can scroll! I'll make add the
scores and make it scroll (with a fixed/floating remove machine button).

**Comment by scottwainstock** [comment]
597ba5a04c0fad33e8b395d9ba2443fe9b1d52d1

**Comment by scottwainstock** [comment]
Everything except the ability to add high scores: 62db8f0b0726e719c55496ed8db82d2564484fda

**Comment by scottwainstock** [comment]
Return msx info when one is created via the api: https://github.com/scottwainstock/pbm/commit/88deb58ea29eb32fc0013f9c56c82a272e0337a2

**Comment by scottwainstock** [comment]
enter scores: 4a87b92f734025094fc811d7e8ec703a896848bc

**Comment by scottwainstock** [comment]
@RyanTG OK, I think this is done now. We need some styling on the enter condition and enter score pages, I think... pretty basic there right now. Also the LocationMachineEdit screen is all over the place. Some links are buttons, others are clickable text. How do we want to normalize that stuff? All buttons?

**Comment by RyanTG** [comment]
Not sure about all buttons. It might look weird to have so many buttons. But you have a point that at least it will be uniform. Right now, though, I think the clickable text includes words that make it somewhat clear that it should be clicked. Well anyway, tomorrow I'll try to style the page so it looks better. Thanks!

**Comment by RyanTG** [comment]
Should I make a new issue for this? The location detail view has some weird scrolling behavior. 1) there's an empty space (like 40dp) at the bottom, and 2) the entire page isn't scrolling, only the machines are.

**Comment by scottwainstock** [comment]
@RyanTG Y, please.
