### ISSUE TITLE
Search by City

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#51]
Since some of our regions have a lot of cities in them, I think it would be useful to include this search option.  Put it underneath "Lookup by Zone"

**Comment by RyanTG** [comment]
Just leaving a comment on this one to try and "bump" it.

**Comment by RyanTG** [comment]
This is similar to the "search by operator" issue, I think. Just want to make sure you saw it. Not sure if it would have been easier to tackle them both at the same time.

**Comment by scottwainstock** [comment]
Should be done: 2fbb7846a100f9d41ee8d9a42974ade23761c0e9
