### ISSUE TITLE
Show year/man info in the machine dropdown menu

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#52]
When adding a machine to a location, as you type in the textfield, you're shown possible results in the dropdown. But the dropdown doesn't show year/man. So, for example, it's unclear which Star Trek is the correct model. It would be nice to see the year/man info in that dropdown.

**Comment by scottwainstock** [comment]
Add auth_details to add machine requests: 173417d3cccd6361c2c3871b1ca279ddec4476d4

**Comment by scottwainstock** [comment]
This one seems pretty important, so I'm adding it to the auth_required release.

**Comment by scottwainstock** [comment]
Add username to lmx#create response.

**Comment by scottwainstock** [comment]
50012440283e9e8cdf4461d93345d8d593a8c338
c72cfef08ec1b9814b9ea532209c0814841951cb

@RyanTG I think this should be done now, and I fixed the crash when you add machines.
