### ISSUE TITLE
Pintips integration

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#59]
Maybe in between each machine name and the machine comments. "view playing tips on pintips.net" I think it would be useful to include the icon that I added: https://github.com/scottwainstock/pbm/blob/35ff94014437e37a8cdc8d2adbdaabc8d6dc09a5/app/assets/images/open-in-new.png
That indicates that the link will take the user to a different site.

Machines that are part of a group must use a different url. See usage: https://github.com/scottwainstock/pbm/blob/35ff94014437e37a8cdc8d2adbdaabc8d6dc09a5/app/views/location_machine_xrefs/_pintips.html.haml

**Comment by RyanTG** [comment]
This isn't working on the app. Right now, the link just goes to pintips.net, but not to the actual machine entry.

**Comment by RyanTG** [comment]
Turns out I broke it when I changed the textview to a button. And also:

android:autoLink="web"
android:linksClickable="true"

Seemed to be breaking it somehow...
I'm seeing if I can fix it.

**Comment by RyanTG** [comment]
I committed something that sort of fixes it. But the text isn't showing up... strangely. 

Also, I don't think you added the functionality for machines that are part of a group. If it's in a group, then the url should be
http://pintips.net/pinmap/group/57 
with 57 being the group ID.

**Comment by scottwainstock** [comment]
This should add the groups functionality: 3cab7abdd4a98f07caca6928c1ae86c57156606f
