### ISSUE TITLE
Location timestamp

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#61]
Include "Location updated: mm/dd/yyyy"
And "Click to confirm that this location's machine list is up to date"

**Comment by RyanTG** [comment]
And now, with users, it should say "Location last updated: 2016-05-07 by username"

**Comment by scottwainstock** [comment]
Added location_last_updated_by_username to API: https://github.com/scottwainstock/pbm/commit/72c4274d768f97251fde76fd9fda460cd4d0652f

**Comment by scottwainstock** [comment]
"Include "Location updated: mm/dd/yyyy"": f0f1cd9ef5ec172222d5decf345bdb5b029c8955

@RyanTG I feel like this area of the location detail screen needs some styling. It's getting really bulky.

**Comment by RyanTG** [comment]
Thanks. I'll work on it.

**Comment by scottwainstock** [comment]
confirm API endpoint: https://github.com/scottwainstock/pbm/commit/48a410023b292b73aa298697bded7825c8b5fdb0

**Comment by scottwainstock** [comment]
confirm button: 3b0b0e7d9feda53d5436e1a3306c7956859fdb98

@RyanTG I think this is pretty much done... but do we want some kind of popup notification or something after people click the confirm button? Maybe play around with it and let me know how you want it to work.

**Comment by RyanTG** [comment]
I see the confirm button. But I don't see "Location last updated: 2016-05-07 by username"
Though I do see "Thanks for confirming that location." in the log, so the button seems to be registering the click.

**Comment by RyanTG** [comment]
Now I see it. I had to restart the app.

**Comment by scottwainstock** [comment]
@RyanTG What kind of notifications do you think we should have? Reload the location detail page so it shows the last updated data? Just a popup?

**Comment by RyanTG** [comment]
I think just the refresh is enough. Would it be a smooth refresh?

I seem to be having an android studio problem... when I launch the emulator, it's not showing my style updates. It's like gradle isn't functioning correctly, or something. I'll try again later.

**Comment by RyanTG** [comment]
Not sure if it was always this way, but the location details do not scroll. They're fixed on the screen, and only the machines scroll. I can't figure out why. But I don't think the location details should be fixed like that.

**Comment by scottwainstock** [comment]
Date format change: 4573b3b8e7f53c83158fbeb2bc6ac32d4e01fed0

**Comment by scottwainstock** [comment]
popup and refresh: c6b938cec754350ab6fdfad40cb3e968b5b934a1

@RyanTG So you want location details to scroll? Do you have an example of a location where we're losing data because it isn't scrolling?

**Comment by RyanTG** [comment]
Ground kontrol. Only half the screen scrolls. Not much real estate for the machine list.



On July 18, 2016 8:11:14 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>popup and refresh: c6b938cec754350ab6fdfad40cb3e968b5b934a1
>
>@RyanTG So you want location details to scroll? Do you have an example
>of a location where we're losing data because it isn't scrolling?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/61#issuecomment-233518832

-- 
Sent from on high.

**Comment by RyanTG** [comment]
Popup and refresh looks great!

**Comment by scottwainstock** [comment]
Scrolling location data: 2a483d8a30e1709687ba7950ab75ffae4a09f098

@RyanTG You can change those two 150dp values to make the scrollable area bigger.

**Comment by RyanTG** [comment]
This isn't what I was expecting. I may have said the wrong thing. When I said "location details" I meant the entire screen that shows the location details, including the machines. Previously, the name and metadata part of that view was fixed on the page, while the machines would scroll. I wanted the entire page to scroll IF the contents are longer than the screen.

Like, so it just scrolls like a webpage would.

**Comment by scottwainstock** [comment]
Oh OK, I think I know what you mean now. You don't want the location
metadata to be fixed.. you want the whole thing to scroll.

**Comment by RyanTG** [comment]
Yeah, the whole thing. Like it's a listview page.

**Comment by scottwainstock** [comment]
@RyanTG How about that? 42645860b4da1b56cd80b2b00ea732a800c9e10e
