### ISSUE TITLE
app checks for location really often

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#62]
The app is really annoying to use if you have location services turned off. It seems to check for your location on every screen. So, the "can't get a fix on your position" message comes up constantly and it gets in the way. For example, it checks every time you add a machine, on both the machine picker screen and the location details screen. Seems unnecessary. Can we reduce the frequency of this check?

**Comment by RyanTG** [comment]
Brian commented about this in an email a while back. I should look it up. 

Definitely not a priority for this next update.

**Comment by scottwainstock** [comment]
@RyanTG I don't think this is a thing anymore, is it? I haven't been asked in a long time.

**Comment by RyanTG** [comment]
Do you have location services turned off? 

Note that it doesn't show this message in the emulator.
