### ISSUE TITLE
Existing comment is not showing up on "condition report" view

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#65]
If a machine has a comment, and you click the comment, you are then shown the condition report view. In this view, the five most recent comments are displayed. But right now, **sometimes** no comments are visible on that view even though there is a comment for that machine. Explanation:

As far as I can tell, if a condition was added before we implemented the "multiple comments" feature, then that condition is not visible on the "condition report" view. But if it was added after, then it is visible. 

I don't think this is a big deal. But it's a little disorienting when that view says "No conditions" when clearly there IS a condition, but it's only visible in the machine list view.

**Comment by scottwainstock** [comment]
Username bug when adding new conditions: 5d275e8ed2cdb8d46263a887caf2955893930325

@RyanTG Is this working for you now?

**Comment by scottwainstock** [comment]
@RyanTG I think there's a second thing going on here, yeah. Exactly like you said... old comments (which didn't make it into the machine_conditions table) aren't showing up on the detail page. We can fix this in live with a one-time script.

**Comment by RyanTG** [comment]
Closing this because the task has been shifted over to PBM.
