### ISSUE TITLE
Add username to machine comments

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#66]
The timestamp on machine comments should say "Updated: 08-May-2016 by hammer"

("hammer" is a username)

**Comment by scottwainstock** [comment]
5e26119bb97db91ae211ef800db512a2d8c237a0
e9bf9f291168d87418b214cea05eb7630c9afd9f

I think I fixed that css issue you were seeing on the staging site too.

**Comment by RyanTG** [comment]
Ah, I figured it was a javascript issue (because the map wasn't loading).

Anyway, thank you. Is it possible to add the word "by" before the username? 

You're right that this environment is a lot different than rails. In rails, I was able to learn little tidbits of rails from working within the haml files, and make little functionality edits. But here, I'm working with the xml files, and I don't touch the java ones (and can't understand them when I do take a look at them). Layout and functionality seem completely separated.

**Comment by scottwainstock** [comment]
It should have a "by" in there... were you just looking at the xml? The java has a "by" that shows up if there's a username.

**Comment by RyanTG** [comment]
Oh, my mistake. I was just looking at the template design preview (I don't know what that is really called). I should have launched the full emulator.

On June 21, 2016 8:04:24 AM PDT, Scott Wainstock <notifications@github.com> wrote:
>It should have a "by" in there... were you just looking at the xml? The
>java has a "by" that shows up if there's a username.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/66#issuecomment-227469124

-- 
Sent from on high.
