### ISSUE TITLE
Operator support

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#67]
The android app doesn't seem to have any mention of operators. Here is what is missing:

- Lookup by Operator
- Operator listed in the location metadata ("Operated by: Really Cool Operator")
- In the Edit Location view, include Operator as an editable field.

**Comment by scottwainstock** [comment]
Rails endpoints to support this.
https://github.com/scottwainstock/pbm/commit/619c0ed02afb0bbaf638d139820f21ea0b17cfe3

...Android code to follow...

**Comment by scottwainstock** [comment]
lookup by operator: e7ee63d2646487136d14d5117cccd0fe0cfcc8f8

**Comment by scottwainstock** [comment]
Operator listed in the location metadata: d34f6ccbd5f960a240fc76b4227b559c7b999c45

**Comment by scottwainstock** [comment]
Operator update via the API: https://github.com/scottwainstock/pbm/commit/4570504d5c631e10ef9b97e8436d39a32ae3d693

**Comment by scottwainstock** [comment]
Update location in the edit view: b75f4ae01abf9b5fa181bd16cd8ca0f197519cfe

@RyanTG I think that should do it for this ticket.

**Comment by RyanTG** [comment]
Thanks! I'll style the operator listed in metadata, if needed.
