### ISSUE TITLE
login page - link to sign up

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#71]
On the login screen, below the login button we should have:

Not a user?
Sign up here

**Comment by scottwainstock** [comment]
json enabled in devise: https://github.com/scottwainstock/pbm/commit/b243be3f7f19ab4a9c50128424204bbc49a40dc9

**Comment by scottwainstock** [comment]
api signup endpoint: https://github.com/scottwainstock/pbm/commit/6d73465f075ebde372b67d05390bc05904a8af71

**Comment by scottwainstock** [comment]
cd2c4406af772341b30ab171ffcc6446e2738999

@RyanTG This should be done now.

**Comment by RyanTG** [comment]
What do you think of that text I put on the sign up page? Doesn't feel totally right to me...

**Comment by scottwainstock** [comment]
Seems kind of cramped. I had to make it MORE cramped in order to fit it all on a screen.

7c6e2ef2b2ea982923de40b95aaaa37c9ecb68a6

We can back that out if you want, the alternative is making it scroll. And, jeez that feels a little intense for a login page. So, what do YOU think?

**Comment by RyanTG** [comment]
I haven't looked at your update. But I think I should reduce the font size to something way less humongous. I'll do that this weekend.

**Comment by RyanTG** [comment]
Have you checked it out on the device? I know that some of those top margins were there so that the field "hints" could fit (those field hints aren't visible unless you're viewing it on an emulator/device). Just checking to make sure they aren't lost with this update...

**Comment by scottwainstock** [comment]
Emulator only. I haven't looked at a device... but I'm emulating my nexus 5.

**Comment by RyanTG** [comment]
Oh sorry, I was referring to the Sign In page, not the Log In page. I thought you were referring to that here.
