### ISSUE TITLE
Machine detail list, remove empty space when no comments

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#76]
When viewing location details, if a machine doesn't have a comment, then there's some empty space below it. Is it possible to HIDE the empty space if there's no comment? (and I'll work on hiding that spacer, since that's something I added).

See below for an example of how it looks now (Pirates of the Caribbean and TRON).  

![screenshot_1470159482](https://cloud.githubusercontent.com/assets/632682/17338916/5f6cecae-589e-11e6-9fb2-0504018d6423.png)

**Comment by scottwainstock** [comment]
6d639b1c77e7b814691712ed9be12c8a1fd08e6d

@RyanTG I think that should do it.

**Comment by RyanTG** [comment]
Thank ye. Looks great.
