### ISSUE TITLE
machine detail - date format and username

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#82]
DATE FORMAT:

On the location detail view, for a machine comment:
Change the date format from YYYY/MM/DD to MM/DD/YYYY

On the machine detail view, for a machine comment:
Change the date format from MM/DD/YY to MM/DD/YYYY

USERNAME:

On the location detail view, for a machine comment:
It's not showing the username of the person who left the comment

On the machine detail view, for a machine comment:
It SOMETIMES shows the username of the person who left the comment. For example, if I leave a new comment, there's no username showing. If I quit the app and then reopen it and then look at that same comment (within the machine detail view), the username is displayed. But if I then add another comment on that same machine, the username for that previous comment disappears. Again, if I quit the app and reopen it, the usernames for both comments are displayed.

**Comment by scottwainstock** [comment]
username of last update at the lmx level on locations index endpoint: https://github.com/scottwainstock/pbm/commit/8184fa642ce865438c962f2b02a85bac36476f8d

**Comment by scottwainstock** [comment]
tag user_id at lmx level when updating lmx condition: https://github.com/scottwainstock/pbm/commit/ccbacfa4e48696044297c862adb531f8fecc15d1

**Comment by scottwainstock** [comment]
51d567bb16f9d1e1048d6fea92fcc9a9b57733f6
08217703730c80f9cb58c2df5baa34badc9ec4c2

@RyanTG 
I think these commits fix this issue. It changed the way scrolling works on the location detail screen, but it's super weird. The scroll area is massive now. I see where the problem is, but I need to stop looking at it for a while.

**Comment by RyanTG** [comment]
Yeah, that scrolling is weird. 

Thanks for taking care of those dates. I should have tried to figure that out myself...

**Comment by scottwainstock** [comment]
Can we close this one? I can handle the scrolling in issue79.

**Comment by RyanTG** [comment]
I'm still experiencing problems:

- If I leave a machine comment, it doesn't show up in the Location Detail view underneath the machine name.
(I'm guessing it shows up if I close and reopen the app)

- In the machine details, the comment timestamps do not show the username. (again, I'm guessing it shows up if I close/reopen)

**Comment by RyanTG** [comment]
And clicking "Add your high score" opens the "condition report" dialog, not the high score dialog.

**Comment by scottwainstock** [comment]
last_updated_by_username in response for add conditions: https://github.com/scottwainstock/pbm/commit/760c9642eaa13d85f2a7aaa207ffbfe2d7f3525f

**Comment by scottwainstock** [comment]
username in machine_condition json: https://github.com/scottwainstock/pbm/commit/fa125c82637c205fab3d8149e39e27b35a77e79d

**Comment by scottwainstock** [comment]
All items above should be addressed here: 418e92fb5dc5e374a4f15f49072624306efd4ff6

**Comment by scottwainstock** [comment]
Initial list of machine conditions in LocationMachineEdit isn't showing the most recent comments. But, it does after you add a new comment. FIX THIS.

**Comment by RyanTG** [comment]
Tagged because of your comment that there's something to fix.

**Comment by scottwainstock** [comment]
60444dde333d4e5e61a67d8e107f735943a4542f

@RyanTG I think this is done now.

**Comment by RyanTG** [comment]
Yeah, seems great.
