### ISSUE TITLE
Location description

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#85]
We never added a location description to the android app. But I guess we should (even though it's just going to add MORE TEXT to the location view).

I think that if there's no location description, then we should NOT display "click here to enter description/hours/etc". Instead, just have a field in location_edit for a description, and if it's populated, then that will display in the location view above the "click here to confirm machines list" link.

**Comment by scottwainstock** [comment]
@RyanTG I'm a little confused by that second paragraph... if there's no location description, we don't let them edit the description/hours/etc?

**Comment by RyanTG** [comment]
We let them do it through the edit location page.

On August 15, 2016 7:18:17 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG I'm a little confused by that second paragraph... if there's no
>location description, we don't let them edit the description/hours/etc?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/85#issuecomment-239983914

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scottwainstock** [comment]
Without the "click here to enter description/hours/etc" thing, how will they get to the location edit screen when there's no location description?

**Comment by RyanTG** [comment]
I was thinking by just clicking edit location in the menu. if you don't think that's a good idea, we can add the link to the page.

On August 15, 2016 7:20:56 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>Without the "click here to enter description/hours/etc" thing, how will
>they get to the location edit screen when there's no location
>description?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/85#issuecomment-239984262

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scottwainstock** [comment]
Got it, OK. I'll make sure I remove the "click here" thing if they aren't authenticated.

What do you think about reworking the location detail screen to have uniform sizes for the machines we list? I think it looks kind of weird that they are different sizes. This would fix our scrolling issue too.

**Comment by scottwainstock** [comment]
Wait, no, I'm lost... I don't see "click here to enter description/hours/etc" anywhere in the app.

**Comment by scottwainstock** [comment]
@RyanTG 74a116d6d60c6a29a9253f02f5fc91688f79e959

I think that covers it, but let me know. I think with that "click to edit" thing you were talking about website functionality or something? So I got confused.

**Comment by RyanTG** [comment]
"What do you think about reworking the location detail screen to have uniform sizes for the machines we list?"

But if someone leaves a long machine comment, and it's listed below the machine name, then that would increase the height of that machine name box. So how would they all be a uniform height? 

Sorry, I was responding from my phone right before a movie started. Right - "click here to enter description/hours/etc" isn't anywhere on the app. That's what this issue is about. And I was saying that we should NOT add that text placeholder. 

The click to edit thing I'm talking about it is the menu item (like under the three dot menu in the upper right) for editing location metadata. Include location description in that location_edit view. Not sure if you just did this. I haven't pulled the commit yet.

**Comment by RyanTG** [comment]
I think this is resolved.
