### ISSUE TITLE
Fix toolbar/actionbar rendering issues in API 24

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#86]
"In Android Studio, if I view location_edit using API 24, it doesn't render correctly (some error related to the toolbar/actionbar. If I change it to 22, it renders fine. Not sure if that would affect users, or if it's strictly an AS thing."

**Comment by RyanTG** [comment]
A few commits ago I was getting that error, but on another page (I think). I fixed it by adding "Base" to the theme name in the ppm_style.xml. It worked, but then it came back! I may have been on 22 before, though, when I fixed it (I recently updated a bunch of AS stuff).

On August 15, 2016 5:31:01 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>"In Android Studio, if I view location_edit using API 24, it doesn't
>render correctly (some error related to the toolbar/actionbar. If I
>change it to 22, it renders fine. Not sure if that would affect users,
>or if it's strictly an AS thing."
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/86

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RyanTG** [comment]
Is this a critical issue?

**Comment by scottwainstock** [comment]
I think so, yeah. I haven't tried to recreate it yet, but it seems like
something we should fix.

**Comment by RyanTG** [comment]
Not sure if this is related, but I learned that fromHTML is deprecated in android N, and as a result it may produce an error in API 24. https://stackoverflow.com/questions/37904739/html-fromhtml-deprecated-in-android-n

Our rendering error seems like a different issue. But maybe something else is deprecated in API 24.

And I guess we need to fix how we're using fromHtml for future compatibility. Looks like we just need to do something like: Html.fromHtml(mNews.getTitle(),Html.FROM_HTML_MODE_LEGACY);
with that ",Html.FROM_HTML_MODE_LEGACY" added.

**Comment by RyanTG** [comment]
Closing this because I'm not seeing the error anymore when using API 24.

Regarding my comment above, about "fromHTML" - indeed instances of that code are crossed out in Android Studio, with a note saying it's deprecated. Here's the change:
`fromHtml(String) method was deprecated in API level 24. use fromHtml(String, int) instead.`

But I don't know what the "int" should be. So the other option, as I mentioned above, is to add FROM_HTML_MODE_LEGACY.
