### ISSUE TITLE
QA for the auth_required released

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#92]
Do some QA/manual testing once a release candidate is discovered.

**Comment by RyanTG** [comment]
Should we ask admins if they want to test?

**Comment by scottwainstock** [comment]
Y

**Comment by RyanTG** [comment]
Should we use any sort of slick beta testing distribution program, or just directly send them an apk?

**Comment by scottwainstock** [comment]
@RyanTG Looks like the play store lets you have alpha/beta testers for release candidates. So, I guess we should just use that.

**Comment by RyanTG** [comment]
K. I'll wait for that to be set up before sending anything to the admins. Then the message could include a link to sign up (rather than saying, "reply to this saying 'yes' and we'll write down your email address and then sign you up when it's ready.").

**Comment by RyanTG** [comment]
I need to add more emulators to my Android Studio, so I can test with more devices/resolutions.

**Comment by RyanTG** [comment]
We already have an issue for bug-hunting. I don't think this issue is necessary.
