### ISSUE TITLE
"Updated on:" text style

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#94]
I hate to add another issue, but I can't figure this one out.

I'm trying to style the "Updated on: mm/dd/yyyy by ssw" text, on the machine comment meta on the Location Detail view. This is where the code is: https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/LocationDetail.java

Usually the text uses "setText" so I can add "setText(Html.fromHtml..." but that doesn't work here. 

If you look at the location_machine_edit view, that's how I'd like it to be formatted (so, also with bold on "by ssw").

_Updated on:_ mm/dd/yyyy **by ssw**

I just think this would help it stand out from the comment itself.

**Comment by scottwainstock** [comment]
How's this? 4d3f2047857ce8cd4bc8e15e993c15c54f4126e4

**Comment by RyanTG** [comment]
It's sweet. The changes to the java file were way more straightforward than I was expecting. I swear I tried doing that!

I'm tweaking it slightly. I'm not seeing a line break before "updated on...' even though you included \n. So I added a br tag to the html part, and it seems to work fine.
