### ISSUE TITLE
"Location Last Updated" does not update after adding a machine

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#96]
Added a machine to a location and the "location last updated" did not update.

**Comment by RyanTG** [comment]
Added a machine comment, and the location last updated did not update, either.

**Comment by RyanTG** [comment]
Deleted a machine, and the location last updated did not update.

**Comment by scottwainstock** [comment]
Prolly updated on the actual SITE though, right? Not saying we shouldn't
fix this... just asking.

**Comment by RyanTG** [comment]
Yes, it updated on the site.

**Comment by scottwainstock** [comment]
1376d8491b5b0166b7e3bf83221c8beeedff7dff

@RyanTG Should be good.

**Comment by RyanTG** [comment]
Still does not update after leaving a machine comment. 

But it does when you add/remove a machine.

**Comment by scottwainstock** [comment]
@RyanTG This should be the last of it..
ac66aedf518ef56faaa712dfba1c674329788424

**Comment by RyanTG** [comment]
Thanks. Looks good!
