### ISSUE TITLE
Remove rank/initials from high score section

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#97]
Remove rank/initials from high score section

**Comment by scottwainstock** [comment]
fc38e943e08c6dc00bea528a55947c9e9a049116

**Comment by RyanTG** [comment]
Just for the record, initials are still in the high score section, and that seems fine to me.

**Comment by scottwainstock** [comment]
Can you show me where? I changed it to username.

**Comment by RyanTG** [comment]
Oh shit, sorry, nevermind. I mixed up "username" and "initials" in my head.
