### ISSUE TITLE
High score sort order

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#99]
Right now the high scores seem to be sorted by the first digit only (or first two digits maybe?). For example, "12,345" shows up above "1,656,656" even though the latter is a higher score.

I think the highest score should be at the top of the list.

**Comment by scottwainstock** [comment]
@RyanTG I think this should do it...

1d652821986401bc5b8f887df755ab10bf8b041c

**Comment by RyanTG** [comment]
Seems good! THX
